### ISSUE TITLE
data/taiwant-holiday-cache.json was expired

### ISSUE THREAD

**Issue by kwhsiung** [ensky/taiwan-holiday.js#4]
[data/taiwant-holiday-cache.json](https://github.com/ensky/taiwan-holiday.js/blob/efdb362210e97cc16fa6c590f124388b266e7d2e/data/taiwan-holiday-cache.json) was expired and missing the holiday data of the year 2021, which will cause unexpected result if we do not provide our cache directory in `temp_dir`, here is the reproduce:
```js
const holiday = require('taiwan-holiday');

holiday.init(/* do not provide the temp_dir manually */)
	.then(() => {
		holiday.isHoliday('2021/1/1'); // expect true, but return false
	});
```

**Comment by ensky** [comment]
It should be fixed, thanks for report!
